# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  # https://developer.hashicorp.com/vagrant/docs/vagrantfile/machine_settings

  # You can search for boxes at https://vagrantcloud.com/search.
  config.vm.box = "archlinux/archlinux"
  config.vm.box_check_update = true
  config.vm.disk :disk, size: "128GB", primary: true
  config.vm.hostname = "mimesis"
  config.vm.define "mimesis" do |_|
  end

  # Provider-specific configuration
  # https://developer.hashicorp.com/vagrant/docs/providers/virtualbox/configuration
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false # headless
    vb.name = "mimesis"
    vb.memory = "32768" # MiB
    # https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm
    vb.customize ["modifyvm", :id,
                  "--cpus", "16",
                  "--hwvirtex", "on",
                  "--nested-hw-virt", "on",
                  "--firmware", "efi64",
                  "--vm-process-priority", "high",
                  "--vrde", "off", # disable vbox remote desktop extension
                  "--audio-enabled", "off",
    ]
  end

  # Disable directory sharing. We want to have a separate copy in the VM.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Enable provisioning with a shell script.
  # https://developer.hashicorp.com/vagrant/docs/provisioning

  config.vm.provision "configs", type: "file", source: "configs", destination: "$HOME"
  config.vm.provision "system", type: "shell", privileged: true, inline: <<-SCRIPT
    set -ex
    # Resize root partition and filesystem
    pacman -Sy --needed --noconfirm parted
    echo -e 'Fix\\n3\\nYes\\n100%\\n' | parted ---pretend-input-tty /dev/sda resizepart 3 100%
    btrfs filesystem resize max /
    # Set up locale
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
    echo "LANG=en_US.UTF-8" > /etc/locale.conf
    locale-gen
  SCRIPT
  config.vm.provision "setup", type: "shell", after: "system", privileged: false, reboot: true, inline: <<-SCRIPT
    set -ex
    sudo pacman -Sy --needed --noconfirm git
    git clone https://github.com/kyechou/mimesis.git "$HOME/mimesis"
    cd "$HOME/mimesis"
    ./depends/setup.sh
    sudo pacman -Syu --needed --noconfirm vim tmux less bash-completion
  SCRIPT
end
